# Example of configuration file tuning adsorption desorption parameters for
# Pa and Th isotopes.

config_file_path: "/storage/homefs/uh24x373/bgc_bern/bayesian_optimization/bayesian_optimization/config_isotopes.yaml"

# Provide the paths where this scripts can be found. They should all be in the directory of this module
bern3d_script: "/storage/homefs/uh24x373/bgc_bern/shared/runscripts/run_bern3d_v3_omp_6cores.sh"
postprocessing_script: "/storage/homefs/uh24x373/bgc_bern/bayesian_optimization/runscripts/run_postprocessing.sh"
optimizer_script: "/storage/homefs/uh24x373/bgc_bern/bayesian_optimization/runscripts/run_optimizer.sh"
python_scripts: "/storage/homefs/uh24x373/bgc_bern/bayesian_optimization/"

# Define some expected times for the model to run, and for the python scripts (usually a few minutes)
bern3d_script_time: "06:00:00"
postprocessing_script_time: "00:05:00"
optimizer_script_time: "00:05:00"

# Name of the simulation and where the output type and timescale to use (usally only full and ave)
simulation_name_bern3d: "Isotopes"
output_type_bern3d: "full"
output_timescale_bern3d: "ave"
# You may also restart from past simulations using the wildcard simulation argument
# by entering the shared name of the simulations e.g. past_simulations* or None, which will be
# converted into *. The past simulation should be in output_files_restart and the simulation name
# of restarts should be in simulation_name_restart
wildcard_simulation: !!python/none

# The path to the working directory
work_directory: "/storage/scratch/users/uh24x373/Optimization_isotopes/"
# keep as None if the output should be in the workdirectory
output_files_bern3d: !!python/none
output_dir_optimizer: !!python/none

# Path to initialization in case of simulation initialization. In case of None, use !!python/none
simulation_name_restart: !!python/none
output_files_restart: !!python/none

# For Bern3d-v3, the flag has to be set to False
bern3d_f90: True
template_name_bern3d: "RUNNAME"
bern3d_template: "/storage/homefs/uh24x373/bgc_bern/bern3d_f90/run/"

# Path of the validation data
validation_data_path: "/storage/research/climate_climtip/testorf/data/"

# The number of iterations to run the Bayesian optimization algorithm
max_iterations: 100
max_stable_iterations: 15
# Targets for POC, CaCO3 and NPP in Pg C yr-1
# Targets for Opal in Tg Si yr-1
# Targets for amoc in °C
target_values:
 target_amoc: !!python/none
 target_poc: !!python/none
 target_caco3: !!python/none
 target_opal: !!python/none
 target_npp: !!python/none

# Path to file with parameters to be optimized
# The path should contain a keyword {my_simulation} which will be replaced by the simulation name
parameter_file: ".bgc.parameter"
bern3d_restart_files: "/storage/homefs/uh24x373/bgc_bern/bern3d-v3/results/Spi240_3__*"

parameter_bounds:
  sigmaPaPOC: !!python/tuple [0.,0.1]
  sigmaPaCa: !!python/tuple [0.,0.1]
  sigmaPaOp: !!python/tuple [0.,0.1]
  sigmaPaDu: !!python/tuple [0.,0.1]
  PaDesConst: !!python/tuple [1,10]
  pavelscale: !!python/tuple [0.03,0.16]
  bgcWterrPa: !!python/tuple [10000,25000]

initialization_type: "lhs"
isotope: "Pad"
n_initialization: 10
surrogate_type: "RF"
acquisition_type: "EI"
batchsize: 3
acquisitition_optimizer: "auto"
job_number: -1
