# Bayesian optimization configuration file
# This file contains the configuration parameters for the Bayesian optimization
# algorithm. The parameters are used to configure the Bayesian optimization
# algorithm and the optimization process.

config_file_path: "/storage/homefs/uh24x373/bgc_bern/bern3d_tools/bayesian_optimization/bayesian_optimization/config_new.yaml"

# The path to the scripts used to run the model, postprocessing and optimizer
bern3d_script: "/storage/homefs/uh24x373/bgc_bern/bern3d_tools/bayesian_optimization/runscripts/run_bern3d_f90_sequential.sh"
postprocessing_script: "/storage/homefs/uh24x373/bgc_bern/bern3d_tools/bayesian_optimization/runscripts/run_postprocessing.sh"
optimizer_script: "/storage/homefs/uh24x373/bgc_bern/bern3d_tools/bayesian_optimization/runscripts/run_optimizer.sh"
python_scripts: "/storage/homefs/uh24x373/bgc_bern/bern3d_tools/bayesian_optimization/"

bern3d_script_time: "10:00:00"
postprocessing_script_time: "01:00:00"
optimizer_script_time: "01:00:00"

# Name of the simulation and type of data to use
simulation_name_bern3d: "NPZD"
output_type_bern3d: "full"
output_timescale_bern3d: "ave"
wildcard_simulation: None

# The path to the working directory
work_directory: "/storage/scratch/users/uh24x373/NPZD_tuning_1000/"
output_files_bern3d: None
output_dir_optimizer: None

# Path to initialization in case of simulation initialization. In case of None, use !!python/none
simulation_name_restart: !!python/none
output_files_restart: !!python/none

# For Bern3d-v3, the flag has to be set to False
bern3d_f90: True
bern3d_executable_name: "RUNNAME"
bern3d_template: "/storage/scratch/users/uh24x373/bern3d_f90/run/"
initialization_file: None

# Path where you want to store the output of the optimizer
validation_data_path: "/storage/scratch/users/uh24x373/bern3d_f90/run/"

# The number of iterations to run the Bayesian optimization algorithm
max_iterations: 100
max_stable_iterations: 15

# Targets for POC, CaCO3 and NPP in Pg C yr-1
# Targets for Opal in Tg Si yr-1
target_values:
 target_amoc: 15.5
 target_poc: 9.76
 target_caco3: 1.87
 target_opal: 190.73
 target_npp: 60.0

# Path to file with parameters to be optimized
# The path should contain a keyword {my_simulation} which will be replaced by the simulation name
bern3d_parameter_file: ".npzd.parameter"
bern3d_restart_files: "/storage/scratch/users/uh24x373/bern3d_f90/results/Spinup2*"

parameter_bounds:
  a_growth_diaz: !!python/tuple [0.3,1.7]
  a_growth_cocc: !!python/tuple [0.3,1.7]
  a_growth_diat: !!python/tuple [0.5,3.0]
  a_growth_other: !!python/tuple [0.3,1.7]
  graze_max: !!python/tuple [0.1,1.1]
  mort_zoo: !!python/tuple [0.0,0.2]
  pref_diaz: !!python/tuple [0.1,2.0]
  pref_cocc: !!python/tuple [0.1,2.0]
  pref_diat: !!python/tuple [0.1,2.0]
  pref_other: !!python/tuple [0.1,2.0]
  pref_det: !!python/tuple [0.1,2.0]
  pref_self: !!python/tuple [0.1,2.0]


initialization_type: "random" # Type of initialization
isotope: "dic_alk_po4_sio_npp_poc_caco3_opal"      # Target of interest
n_initialization: 5             # Number of initializations 10
surrogate_type: "RF"              # Surrogate type
acquisition_type: "gp_hedge"            # Acquisition type
batchsize: 10                     # Batch size
acquisitition_optimizer: "auto"   # Acquisition optimizer
job_number: -1                     # Job number
