# Bayesian optimization configuration file
# This file contains the configuration parameters for the Bayesian optimization
# algorithm. The parameters are used to configure the Bayesian optimization
# algorithm and the optimization process.

config_file_path: "/storage/homefs/uh24x373/bgc_bern/bayesian_optimization/bayesian_optimization/config.yaml"

# The path to the scripts used to run the model, postprocessing and optimizer
bern3d_script: "/storage/homefs/uh24x373/bgc_bern/bayesian_optimization/runscripts/run_bern3d_f90.sh"
postprocessing_script: "/storage/homefs/uh24x373/bgc_bern/bayesian_optimization/runscripts/run_postprocessing.sh"
optimizer_script: "/storage/homefs/uh24x373/bgc_bern/bayesian_optimization/runscripts/run_optimizer.sh"

bern3d_script_time: "00:40:00"
postprocessing_script_time: "02:00:00"
optimizer_script_time: "00:10:00"

# Path to output directory of bern3d
simulation_name_bern3d: "Bay_test"
output_type_bern3d: "timeseries"
output_timescale_bern3d: "ave"
work_directory: "/storage/scratch/users/uh24x373/Bayesian_optimizer_test/"
output_files_bern3d: "/storage/scratch/users/uh24x373/Bayesian_optimizer_test/results/"

# For Bern3d-v3, the flag has to be set to False
bern3d_f90: True
template_name_bern3d: "RUNNAME"
bern3d_template: "/storage/homefs/uh24x373/bgc_bern/bern3d_f90/run/"
initialization_file: "/storage/homefs/uh24x373/bgc_bern/bern3d-v3/results/Spi240_3__.00001765_full_inst.nc"

# Path where you want to store the output of the optimizer
validation_data_path: "/storage/research/climate_climtip/testorf/data/"
output_dir_optimizer: "/storage/scratch/users/uh24x373/Bayesian_optimizer_test/bayesian_optimization/"

# The number of iterations to run the Bayesian optimization algorithm
max_iterations: 3

# Path to file with parameters to be optimized
# The path should contain a keyword {my_simulation} which will be replaced by the simulation name
parameter_file: "{simulation_name_bern3d}.bgc.parameter"
# Parameters to be optimized (line number in the parameter file)
parameter_mapping:
  sigmaPaPOC: 396
  sigmaPaCa: 397
  sigmaPaOp: 398
  sigmaPaDu: 399
  PaDesConst: 388
  pavelscale: 379
  bgcWterrPa: 383

parameter_bounds:
  sigmaPaPOC: !!python/tuple [0.,0.1]
  sigmaPaCa: !!python/tuple [0.,0.1]
  sigmaPaOp: !!python/tuple [0.,0.1]
  sigmaPaDu: !!python/tuple [0.,0.1]
  PaDesConst: !!python/tuple [1,10]
  pavelscale: !!python/tuple [0.03,0.16]
  bgcWterrPa: !!python/tuple [10000,25000]

initialization_type: "lhs" # Type of initialization
isotope: "Pad"                    # Isotope of interest
n_initialization: 10               # Number of initializations
surrogate_type: "RF"              # Surrogate type (GP currently not supported)
acquisition_type: "EI"            # Acquisition type
batchsize: 3                      # Batch size
acquisitition_optimizer: "auto"   # Acquisition optimizer
job_number: -1                     # Job number
