# Example of configuration file tuning wind and circulation paremeters with the targets of
# salinity, temperature, ideal age and AMOC strength.
# This tuning was done to try and set the wind stress factor to 1

config_file_path: "/storage/homefs/uh24x373/bgc_bern/refactor/bern3d_tools/bern3d_tools/bayesian_optimization/bayesian_optimization/config_salt_temp_ida_amoc.yaml"

# Provide the paths where this scripts can be found. They should all be in the directory of this module
# "/storage/homefs/uh24x373/bgc_bern/bern3d_tools/shared/runscripts/run_bern3d_f90_omp_8cores.sh"
bern3d_script: "/storage/homefs/uh24x373/bgc_bern/refactor/bern3d_tools/bern3d_tools/shared/runscripts/run_bern3d_f90_omp_8cores.sh"
postprocessing_script: "/storage/homefs/uh24x373/bgc_bern/refactor/bern3d_tools/bern3d_tools/bayesian_optimization/runscripts/run_postprocessing.sh"
optimizer_script: "/storage/homefs/uh24x373/bgc_bern/refactor/bern3d_tools/bern3d_tools/bayesian_optimization/runscripts/run_optimizer.sh"
python_scripts: "/storage/homefs/uh24x373/bgc_bern/refactor/bern3d_tools/bern3d_tools/bayesian_optimization/"

# Define some expected times for the model to run, and for the python scripts (usually a few minutes)
bern3d_script_time: "10:00:00"
postprocessing_script_time: "01:00:00"
optimizer_script_time: "01:00:00"

# Name of the simulation and where the output type and timescale to use (usally only full and ave)
simulation_name_bern3d: "Wind"
output_type_bern3d: "full"
output_timescale_bern3d: "ave"
# You may also restart from past simulations using the wildcard simulation argument
# by entering the shared name of the simulations e.g. past_simulations* or None, which will be
# converted into *. The past simulation should be in output_files_restart and the simulation name
# of restarts should be in simulation_name_restart
wildcard_simulation: !!python/none

# The path to the work directory (best to use scratch)
work_directory: "/storage/scratch/users/uh24x373/Optimization_wind_V2/"
# keep as None if the output should be in the workdirectory
output_files_bern3d: !!python/none
output_dir_optimizer: !!python/none

# Path to initialization in case of simulation initialization. In case of None, use !!python/none
simulation_name_restart: !!python/none
output_files_restart: !!python/none

# For Bern3d-v3, the flag has to be set to False
bern3d_f90: True
bern3d_executable_name: "RUNNAME"
bern3d_template: "/storage/homefs/uh24x373/bgc_bern/particle_flux/bern3d_f90/run/"

# Path to the validation dataset
#validation_data_path: "/storage/homefs/bm25v947/data/tracers/fripiat_n15_reformatted.tab"
validation_data_path: "/storage/homefs/uh24x373/bgc_bern/particle_flux/bern3d_f90/run/world_68x46.observations.nc"

# The number of iterations to run the Bayesian optimization algorithm
use_reference_simulation: False
max_iterations: 2
max_stable_iterations: 15
# Targets for POC, CaCO3 and NPP in Pg C yr-1
# Targets for Opal in Tg Si yr-1
# Targets for amoc in °C
target_values:
 target_amoc: 14.5
 target_poc: !!python/none
 target_caco3: !!python/none
 target_opal: !!python/none
 target_npp: !!python/none

# Path to file with parameters to be optimized
bern3d_parameter_file: ".ocn.parameter,.ebm.parameter"
bern3d_restart_files: !!python/none

parameter_bounds:
  rel: !!python/tuple [0.7, 1.0]
  diff-iso: !!python/tuple [500.0, 1500.0]
  kappa0: !!python/tuple [1.0e-5,3.0e-5]
  gmkap: !!python/tuple [1000,3000]
  idrag: !!python/tuple [1.0,2.0]
  drgf: !!python/tuple [1.5, 4.3]
  brinerejfrac: !!python/tuple [0.6,1.0]

fixed_values:
  scf: 1.0

use_penalty: False

initialization_type: "lhs"
tuning_target: "temp_salt_ida_amoc"
#tuning_target: "custom"
n_initialization: 3
surrogate_type: "RF"
acquisition_type: "gp_hedge"
batchsize: 3
acquisitition_optimizer: "auto"
job_number: -1

# Standard Bern3D setup for optimization
variable_names:
  dic:
    sim: "DIC"
    obs: "dic"
  alk:
    sim: "ALK"
    obs: "alk"
  po4:
    sim: "PO4"
    obs: "po4"
  sio:
    sim: "SiO"
    obs: "sio"
  no3:
    sim: "NO3"
    obs: "no3"
  temp:
    sim: "TEMP"
    obs: "temp"
  salt:
    sim: "S"
    obs: "salt"
  ida:
    sim: "IdealAge"
    obs: "ida"
  amoc:
    sim: "OPSIA_max"
    obs: !!python/none
  npp:
    sim: "NPZD_NPP"
    obs: !!python/none
  poc:
    sim: "EXPORT_POM"
    obs: !!python/none
  caco3:
    sim: "EXPORT_CACO3"
    obs: !!python/none
  opal:
    sim: "Export_OPAL"
    obs: !!python/none